### ISSUE TITLE
加载模型超时

### ISSUE THREAD

**Issue by Primary-Traxex** [yannliao/threejs-example-for-miniprogram#10]
设置不检测域名之后，还是会加载超时。我猜测是这个域名[https://threejs.org](url)，延迟的原因，如果可以把模型放在云开发里面会更加好，或者放在本地开启nginx代理然后修改host，你说呢。

**Comment by Primary-Traxex** [comment]
说一下我的思路。
1. 注册gitee、github，到github中fork Three项目，然后到gitee中新建项目，点击关联github，选择该three项目。到windows中使用git下载该gitee项目到本地。
2. 然后下载nginx，代理该项目文件夹。例如
`server {
        listen  8888;
        server_name location three.ziyuan.com;

        location / {
            root  D:/test/html/Three.js/;
            index index.html;
        }

        error_page   500 502 503 504 404 403  /50x.html;
        location = /50x.html {
            root   html;
        }
    }`
3. 去本地中修改host，例如
`192.168.43.197 www.aaa.com #本地环境测试`
4. 修改本项目中用到的URL链接域名为`www.aaa.com `

**Comment by Primary-Traxex** [comment]
![image](https://user-images.githubusercontent.com/16198816/69217274-3c768400-0ba9-11ea-9a34-5b00d1f7c127.png)
示例

**Comment by Primary-Traxex** [comment]
昨天发现小程序云开发可以上传文件并且将文件以cdn形式让外部调用
1. 把three.js上的资源上传到云开发
![image](https://user-images.githubusercontent.com/16198816/69322777-74042f80-0c80-11ea-85e6-c7ff8aa3a186.png)

2. 修改小程序对应位置的链接。
![image](https://user-images.githubusercontent.com/16198816/69322928-b594da80-0c80-11ea-9065-3929982007c8.png)

**Comment by yannliao** [comment]
是的  然而我的云没有空间了   或者自己用 node  起一个  localhost 服务也可以～
