### ISSUE TITLE
真机调试模式一片空白，小米9

### ISSUE THREAD

**Issue by UPtreeMonkey** [yannliao/threejs-example-for-miniprogram#11]
手机上预览是ok的，真机调试模式就一片空白，不知道为啥

**Comment by UPtreeMonkey** [comment]
查了下发现是，小程序不支持真机调试webgl
https://developers.weixin.qq.com/community/develop/doc/0000c6ce010448c95af85422251400

**Comment by yannliao** [comment]
小程序不支持webgl真机调试  用预览功能
