### ISSUE TITLE
建议：可以建立一个qq群，以供大家讨论。。

### ISSUE THREAD

**Issue by liuxin2322** [yannliao/threejs-example-for-miniprogram#5]
小程序适配threejs有个qq群，大家可以讨论更多细节。。然后你也可以获得更多的反馈，嘻嘻。

**Comment by liuxin2322** [comment]
就叫“threejs 小程序群”就挺好的

**Comment by liuxin2322** [comment]
还有一个建议，老哥，你这个项目真的好，有许多适配了的example。（这比微信官方只是干巴巴的一个例子好多了）但是真心的在github不能直接搜到你，我在微信开发者网站才注意到这个项目，所以建议你起一个有识别性的名字，例如“mpthree”:miniprogram three.js

**Comment by liuxin2322** [comment]
我个人会使用three.js做这个项目会很长久，所以也会尽我所能一起帮忙维护这个项目。:grinning:

**Comment by yannliao** [comment]
可以可以～

**Comment by yannliao** [comment]
可以加我qq 1187954393  建个群～

**Comment by liuxin2322** [comment]
@yannliao 好的，已发送请求:grinning:
