### ISSUE TITLE
GLTFloader.js加载纹理貌似有问题

### ISSUE THREAD

**Issue by SummerisYoung** [yannliao/threejs-example-for-miniprogram#9]
![image](https://user-images.githubusercontent.com/49905884/69143454-fadfcd80-0b03-11ea-8968-8b67cfa8624c.png)
如图，小程序不是不能用window嘛，这里加载会报Cannot read property 'URL' of undefined的错误，导致纹理加载不了。。。

**Comment by yannliao** [comment]
看例子～  texture  用 TextureLoader

**Comment by yannliao** [comment]
小程序loadTexture 中不使用window.URL
